name: Python build container

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]

    steps:
      - name: Init setup
        run: echo "Init setup..."
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Build Container
        run: |
          docker build -t fastapi-postail-response .
      - name: Pytest
        run: |
          docker run -it fastapi-postail-response pytest --pyargs app
      - name: Test with pytest
        run: |
          echo "finished"
